- name: Ping site
  shell: ping -c 1 -w 2 google.com
  register: ping_result

- name: Ping result
  debug:
    msg: "{{ ping_result.stdout_lines }}"

- name: Ping other site
  shell: ping -c 1 -w 2 drei.at
  register: ping_result

- name: Ping result
  debug:
    msg: "{{ ping_result.stdout_lines }}"


- name : Dump extra vars
  debug:
    msg: "{{foo}}"